name: Main

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    env:
      LOCAL_REPO: img2vec-keras
      REMOTE_REPO: semitechnologies/img2vec-keras
      MODEL_NAME: resnet50
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Login to Docker Hub
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and test
        run: |
          cicd/build.sh || exit 1
          cicd/test.sh || exit 1
      - name: Deploy
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          export GIT_TAG=${GITHUB_REF##*/}
          cicd/docker_push.sh || exit 1

